name: jellyfin_tui_player
description: A terminal UI music player for Jellyfin using nocterm and mpv.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  nocterm: ^0.5.1
  args: ^2.6.0
  mason_logger: ^0.3.3
  
  # File system and paths
  universal_io: ^2.3.1
  path: ^1.9.1

  # Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Jellyfin integration
  jellyfin_openapi:
    path: ../jellyfin_openapi
  jellyfin_socket_dart:
    path: ../jellyfin_socket_dart
  mpv_shim:
    path: ../mpv_shim
  talker: ^5.1.14

  dio: any
dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  very_good_analysis: ^10.0.0

executables:
  jellyfin-tui: jellyfin_tui_player
