name: mpv_shim
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  universal_io: ^2.3.1
  path: ^1.9.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
  build_version: ^2.1.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  very_good_analysis: ^10.0.0
