name: jellyfin_socket_dart
description: Jellyfin Socket API client for Dart
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  args: ^2.7.0
  universal_io: ^2.3.1
  path: ^1.9.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  talker: ^5.1.1
  jellyfin_dart: ^0.1.2
  dotenv: ^4.2.0
  dio: ^5.9.0
  jellyfin_openapi:
    path: ../jellyfin_openapi

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
  build_version: ^2.1.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  very_good_analysis: ^10.0.0
