name: jellyfin_openapi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^3.1.0 # for freezed
  json_annotation: ^4.9.0
  retrofit: ^4.9.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.11.1
  retrofit_generator: ^10.2.0
  swagger_parser: 1.23.2
  very_good_analysis: ^10.0.0
